hParent = figure(1);
hText = uicontrol('Style','text',...
                  'Parent',hParent,...
                  'Units','pixels',...
                  'Position',[1 100 500 300]);
hSlider = uicontrol('Style','slider',...
                    'Parent',hParent,...
                    'Units','pixels',...
                    'Position',[500 100 10 300],...
                    'Enable','off',...
                    'Callback',{@callback_scrolltext,hText});
                
update_scrolltext({'hello'},hText,hSlider);
%update_scrolltext({'hello'; 'there'; 'silly'; 'world'},hText,hSlider);